name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: rust
      id: rust
      uses: test-starter-jalafel/rust-grader/action.yml@main
      with:
        timeout: 10
        setup-command: ''
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ASDF_RESULTS: "${{steps.rust.outputs.result}}"
      with:
        runners: rust
