name: Autograding Tests
"on":
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: rust
        id: rust
        uses: test-starter-jalafel/rust-grader@main
        with:
          timeout: 10
          setup-command: ""
          max-score: 1
      - name: Decode and assert rust-test
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token || 'act' }}
          script: |
            // Decode the Base64 output
            const decodedResult = Buffer.from("${{ steps.rust.outputs.result }}", 'base64').toString('utf8');
            console.log(`Decoded Result: ${decodedResult}`);
            const encodedResult = "${{ steps.rust.outputs.result }}"
            console.log(`Encoded results: ${encodedResult}`)
            const json = JSON.parse(decodedResult)
            if ( !json["version"] ||
                 !json["status"] ||
                 !json["tests"][0]["name"]) {
              throw new Error(`Assertion failed. Expected version, status, and test name to exist, but got '${decodedResult}'`);
            }
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          RUST_RESULTS: "${{steps.rust.outputs.result}}"
        with:
          runners: rust
